version: "3.9"

services:

  # ------ FastAPI Application ------------------
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: Lobour_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
      - ../uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - Labour_network

  # -------------- PostgreSQL Database ---------------------
  db:
    image: postgres:15-alpine
    container_name: nakka_db
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - Labour_network

  # ------------ Redis Cache --------------------
  redis:
    image: redis:7-alpine
    container_name: nakka_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - Labour_network


# -------------------- Volumes ----------------------
volumes:
  postgres_data:
  redis_data:

# ----------------- Network ----------------------------
networks:
  Labour_network:
    driver: bridge